name = "openframes-fortran"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2023 Jacob Williams"
license = "Apache"
description = "Modern Fortran interface to OpenFrames realtime interactive scientific visualization API"
homepage = "https://github.com/jacobwilliams/openframes-fortran"

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = true